### ISSUE TITLE
PagePathHistory::getPage() - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language_id' in 'field list'

### ISSUE THREAD

**Issue by q2apro** [ryancramerdesign/ProcessWire#2011]
Having many of such erros in my logs: 

    PagePathHistory::getPage() - SQLSTATE[42S22]: Column not found: 1054 Unknown column 'language_id' in 'field list'

They seem to come from calling the URL `en/http404`.

How to fix that?

**Comment by ryancramerdesign** [comment]
What version of ProcessWire? It looks like the module database schema is older than the module version and perhaps schema didn't update with the module version. I'm not sure why that module upgrade might have failed, but I've just pushed an update to the module to serve as a redundancy for that situation. The next time that error occurs, it will attempt to manually update the db schema. Please let me know if it resolves it. Thanks.

**Comment by q2apro** [comment]
Hi Ryan, I am using `ProcessWire 3.0.28 devns`. 

Before applying this fix, I just saw that the fix you did is with PW 2.x and the file itself is much smaller (7 KB) than the one I am suing (13 KB). 

Is the fix (adding the line into the PagePathHistory.module at the appropriate position) the same for 3.0 then?

Thanks,
Kai

**Comment by ryancramerdesign** [comment]
The fix I just added is on 3.x (3.0.31). If you click the link above in
this thread, that should take you there.

**Comment by q2apro** [comment]
I have added the line but the error message still appears in the logs .(

**Comment by q2apro** [comment]
I have added the fix, now a new error appears: 

```
Error: Uncaught Error: Call to a member function size() on boolean in site/assets/cache/FileCompiler/site/templates/basic-page.php:14 
Stack trace: #0 wire/core/TemplateFile.php(219): require() #1 [internal function]: ProcessWire\TemplateFile->___render() #2 wire/core/Wire.php(347): call_user_func_array(Array, Array) #3 wire/core/WireHooks.php(548): ProcessWire\Wire->_callMethod('___render', Array) #4 wire/core/Wire.php(370): ProcessWire\WireHooks->runHooks(Object(ProcessWire\TemplateFile), 'render', Array) #5 wire/modules/PageRender.module(503): ProcessWire\Wire->__call('render', Array) #6 [internal function]: ProcessWire\PageRender->___renderPage(Object(ProcessWire\HookEvent)) #7 mydomain-de (line 14 of site/assets/cache/FileCompiler/site/templates/basic-page.php)
```

**Comment by ryancramerdesign** [comment]
@q2apro I don't think that's related, as it appears to just be a parse error in one of your front-end template files (basic-page.php). Look for a typo or something on line 14 of /site/templates/basic-page.php

**Comment by q2apro** [comment]
Thanks a lot @ryancramerdesign Indeed it was my co-developer who had left a line there. Issue fixed. Thanks.
